apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: filippetran/ambulance-ufe
  newName: filippetran/ambulance-ufe
  newTag: 1.1.0
  newName: filippetran/ambulance-wl-webapi
  newTag: 1.1.0

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: fp-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  fp-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1